trigger:
  batch: true

pr: 
  branches:
    include:
    - master
 
pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/BuildMonitor.sln'
  buildPlatform: 'Any CPU with x64 Installer'
  buildConfiguration: 'Release'
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 9'
  inputs:
    version: 9.x

- task: Cache@2
  displayName: 'NuGet Pipeline Cache'
  inputs:
    key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
    restoreKeys: |
       nuget | "$(Agent.OS)"
       nuget
    path: '$(NUGET_PACKAGES)'
    
- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore /p:Platform="$(buildPlatform)"'
